### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by TorstenLiu** [sanonz/hexo-theme-concise#1]
你好，很感谢你贡献的主题！
你的主题非常简洁漂亮，但是我在使用时出现了一点问题，发现并不能如意的渲染正确的界面，这让我很困扰。

**Comment by sanonz** [comment]
什么问题详细一点嘛 :wink:

**Comment by TorstenLiu** [comment]
<img src="http://www.torstenliu.me/HBuilder/Hex/problem.png"/>

**Comment by sanonz** [comment]
这里的说明遗漏了，已补上：[安装前提](/Sanonz/hexo-theme-concise/blob/master/README.md#前提)，感谢反馈哈

**Comment by TorstenLiu** [comment]
Very Good!!!
完美解决，Thank you so much!
