### ISSUE TITLE
求指教

### ISSUE THREAD

**Issue by ZhangWren** [sanonz/hexo-theme-concise#10]
![2r9 3x r j0s 31zo 1uq7](https://user-images.githubusercontent.com/25240164/39168648-3eecb72e-47c7-11e8-8acc-8fac01f82ec4.png)
我是按照教程来的，git clone 下来之后啥都没动，但是左侧菜单和头像都不显示，这是为啥啊

**Comment by sanonz** [comment]
配置文件 `themes/concise/_config.example.yml` 重命名为 `themes/concise/_config.yml` 了吗？

**Comment by ZhangWren** [comment]
@sanonz 搞出来了，粗心了下
