### ISSUE TITLE
_config.yml root设置内容无法获取静态资源

### ISSUE THREAD

**Issue by Yuan-SY** [sanonz/hexo-theme-concise#31]
hi,觉得您的hexo concise主题不错，试用了一下，发现如果_config.yml 的root选项设置内容，就无法获取静态资源了，应该是url中缺少root导致的

**Comment by sanonz** [comment]
站点根目录当时没有考虑到，晚点抽个时间适配下哈

**Comment by sanonz** [comment]
修复了哈，你有时间再试下，欢迎继续使用~

**Comment by Yuan-SY** [comment]
感谢，已经正常了
