### ISSUE TITLE
bug：导航栏tags标签点击不出现tag列表

### ISSUE THREAD

**Issue by YuhsiHu** [sanonz/hexo-theme-concise#32]
你好！我的博客中使用了这个主题，在给文章正常添加tag之后，也使用了hexo new tags命令创建tags.md，但是导航栏的tags点击之后只会显示如下状况，而文章内显示的tags是能正常点击显示关键词归档的，请问是什么原因呢？希望尽快解答，谢谢！
![tags bug](https://user-images.githubusercontent.com/34529345/65760987-9716d500-e150-11e9-98c8-58027ee84876.png)

**Comment by sanonz** [comment]
这个命令是使用默认布局创建页面
要使用下边命令指定tag布局创建页面
```bash
$ hexo new tags "标签"
```

**Comment by YuhsiHu** [comment]
我删除了之前的默认布局页面标签和文件夹。
“标签”中的汉字是必须这么写，还是我想创建“深度学习”的标签，其中就填写“深度学习”呢？
如果使用该命令进行了创建，那么md文件里面的tags键值需要补充什么吗？
谢谢你的解答！这款主题非常棒！

**Comment by YuhsiHu** [comment]
1.我使用了如下命令
`$ hexo new tags "标签"`
2.我进入了文章归档，发现里面将标签也作为了一篇（因为标签.md和文件夹都在post下）
3.通过文章归档点进标签可以正常查看，但是侧边栏的Tags进入依旧不能找到页面
![bugreport1](https://user-images.githubusercontent.com/34529345/65813357-d7d12580-e206-11e9-97b2-8c4be1770143.png)
![bugreport2](https://user-images.githubusercontent.com/34529345/65813359-db64ac80-e206-11e9-9fa9-9fa4f8dd33f0.png)
![bugreport3](https://user-images.githubusercontent.com/34529345/65813361-de5f9d00-e206-11e9-99b5-dc6e2f8c3a71.png)

**Comment by sanonz** [comment]
上边搞错了，不好意思哈，文档也写错了，我同步修改下，使用这个解决
```bash
$ hexo new page tags
INFO  Created: E:\blog\source\tags\index.md
```
把这个 `source\tags\index.md` 文件

```yam
---
title: tags
date: 2019-09-29 17:27:33
---
```

改为

```yam
---
title: tags
date: 2019-09-29 17:27:33
layout: tags
---
```

**Comment by YuhsiHu** [comment]
谢谢！问题已解决！这是一个很棒的主题，希望能持续完善！
