### ISSUE TITLE
？！again

### ISSUE THREAD

**Issue by lolifamily** [sanonz/hexo-theme-concise#41]
https://loliblogs.gitee.io/post/hello-world/
![image](https://user-images.githubusercontent.com/47876607/83248258-61daef00-a1d7-11ea-9ac9-ceea5d3fff1b.png)

**Comment by lolifamily** [comment]
https://github.com/loliblogs/discuss-index/issues/2
![image](https://user-images.githubusercontent.com/47876607/83248531-c72ee000-a1d7-11ea-890f-bc19e8be79d3.png)

**Comment by lolifamily** [comment]
@sanonz

**Comment by sanonz** [comment]
这个是因为 hexo 与 github 的 code 解析器不一致未做兼容导致的。
