### ISSUE TITLE
分类页面

### ISSUE THREAD

**Issue by shadowmoon1988** [sanonz/hexo-theme-concise#5]
我希望能够实现像archive一样的分类栏
hexo generate时，可以生成/categories/具体分类/index.html，但是在/categories 下没有index.html
如何实现该功能？

**Comment by shadowmoon1988** [comment]
这是hexo list route的结果
Total: 31
├─┬ 2017
│ └─┬ 12
│   └─┬ 29
│     └─┬ hello-world
│       └── index.html
├─┬ about
│ └── index.html
├─┬ archives
│ ├─┬ 2017
│ │ ├─┬ 12
│ │ │ └── index.html
│ │ └── index.html
│ └── index.html
├── atom.xml
├─┬ categories
│ └─┬ Coding
│   └── index.html
├─┬ css
│ ├── app.css
│ ├── archive.css
│ ├── article.css
│ ├── aside.css
│ ├── footer.css
│ ├── icons.css
│ ├── markdown.css
│ ├── mixin.css
│ ├── monokai-sublime.css
│ ├── nav.css
│ ├── page.css
│ ├── reset.css
│ ├── style.css
│ ├── tags.css
│ ├── vars.css
│ └── widget.css
├─┬ fonts
│ ├── icomoon.eot
│ ├── icomoon.svg
│ ├── icomoon.ttf
│ └── icomoon.woff
├─┬ images
│ └── avatar.jpg
├── index.html
└─┬ tags
  ├─┬ Hexo
  │ └── index.html
  └─┬ Test
    └── index.html

**Comment by sanonz** [comment]
已经添加分类页面，目前比较简约，后期会继续优化，执行一下命令获取

获取最新主题
```shell
cd themes/concise
git pull
```
生成分类页面
```shell
hexo new page categories
```
编辑生成的 categories/index.md 文件，设置布局为分类页面：
```yml
layout: categories
```
访问：domain/categories 页面查看效果

**Comment by shadowmoon1988** [comment]
Thanks, It works fine.
