### ISSUE TITLE
能不能更新一下bootstrap啊

### ISSUE THREAD

**Issue by lolifamily** [sanonz/hexo-theme-concise#50]
能不能更新一下bootstrap啊，v4都有了
@sanonz

**Comment by sanonz** [comment]
没有用到 bootstrap 啊

**Comment by lolifamily** [comment]
scrollspy不是bootstrap啊？@sanonz

**Comment by sanonz** [comment]
scrollspy 是从 bootstrap 单独抽离的一个插件，低版本的向下兼容浏览器会好一些

**Comment by lolifamily** [comment]
能不能把scrollspy CDN化啊 @sanonz
